package model

import (
	"github.com/boundedinfinity/go-commoner/errorer"
)

var (
	ErrJsonSchemaTypeNotFound             = errorer.Errorf("json schema type not found")
	ErrJsonSchemaTypeUnsupported          = errorer.Errorf("json schema type unsupported")
	ErrJsonSchemaTypeUnsupportedv         = errorer.Wrapf(ErrJsonSchemaTypeUnsupported)
	ErrJsonSchemaIdNotFound               = errorer.Errorf("json schema ID not found")
	ErrJsonSchemaIdNotFoundv              = errorer.Wrapf(ErrJsonSchemaIdNotFound)
	ErrJsonSchemaCantResolve              = errorer.Errorf("json schema can't resolve")
	ErrJsonSchemaCantResolvev             = errorer.Wrapf(ErrJsonSchemaCantResolve)
	ErrJsonSchemaIdDuplicate              = errorer.Errorf("json schema ID duplicate")
	ErrJsonSchemaIdDuplicatev             = errorer.Wrapf(ErrJsonSchemaIdDuplicate)
	ErrJsonPathDuplicate                  = errorer.Errorf("json schema path duplicate")
	ErrJsonPathDuplicatev                 = errorer.Wrapf(ErrJsonPathDuplicate)
	ErrJsonSchemaNotFound                 = errorer.Errorf("json schema not found")
	ErrJsonSchemaNotFoundv                = errorer.Wrapf(ErrJsonSchemaNotFound)
	ErrJsonSchemaRefEmpty                 = errorer.Errorf("reference is empty")
	ErrJsonSchemaRefNotFound              = errorer.Errorf("reference not found")
	ErrJsonSchemaRefNotFoundv             = errorer.Wrapf(ErrJsonSchemaRefNotFound)
	ErrJsonSchemaObjectPropertiesNotFound = errorer.Errorf("object properties not found")
	ErrJsonSchemaTypeOrRefNotFound        = errorer.Errorf("json schema type or $ref not found missing")
	ErrJsonSchemaMimeTypeUnsupported      = errorer.Errorf("MIME type unsupported")
	ErrJsonSchemaMimeTypeUnsupportedv     = errorer.Wrapf(ErrJsonSchemaMimeTypeUnsupported)
	ErrJsonSchemaNumberMultipleOfInvalid  = errorer.Errorf("multipleOf must be greater than 0")
	ErrJsonSchemaNumberMultipleOfInvalidv = errorer.Wrapf(ErrJsonSchemaNumberMultipleOfInvalid)
	ErrJsonSchemaArrayMaxContainsInvalid  = errorer.Errorf("maxContains must be greater than 0")
	ErrJsonSchemaArrayMaxContainsInvalidv = errorer.Wrapf(ErrJsonSchemaArrayMaxContainsInvalid)
	ErrJsonSchemaArrayMinContainsInvalid  = errorer.Errorf("minContains must be greater than 0")
	ErrJsonSchemaArrayMinContainsInvalidv = errorer.Wrapf(ErrJsonSchemaArrayMinContainsInvalid)
	ErrJsonSchemaArrayInvalidMaxMin       = errorer.Errorf("maxContains must be greater than minContains")
	ErrJsonSchemaArrayInvalidMaxMinv      = errorer.Wrapf(ErrJsonSchemaArrayInvalidMaxMin)
	ErrJsonSchemaArrayItemsEmpty          = errorer.Errorf("array items is empty")
	ErrJsonSchemaNumberInvalidMaxMin      = errorer.Errorf("maximum must be greater than minimum")
	ErrJsonSchemaNumberInvalidMaxMinv     = errorer.Wrapf(ErrJsonSchemaNumberInvalidMaxMin)
	ErrJsonSchemaStringMaxLength          = errorer.Errorf("maxLength must be greater than 0")
	ErrJsonSchemaStringMaxLengthv         = errorer.Wrapf(ErrJsonSchemaStringMaxLength)
	ErrJsonSchemaStringMinLength          = errorer.Errorf("minLength must be greater than 0")
	ErrJsonSchemaStringMinLengthv         = errorer.Wrapf(ErrJsonSchemaStringMinLength)
	ErrJsonSchemaStringMaxMinLength       = errorer.Errorf("maxLength must be greater than minLength")
	ErrJsonSchemaStringMaxMinLengthv      = errorer.Wrapf(ErrJsonSchemaStringMaxMinLength)
	ErrJsonSchemaObjectMaxProperties      = errorer.Errorf("maxProperties must be greater than 0")
	ErrJsonSchemaObjectMaxPropertiesv     = errorer.Wrapf(ErrJsonSchemaObjectMaxProperties)
	ErrJsonSchemaObjectMinProperties      = errorer.Errorf("minProperties must be greater than 0")
	ErrJsonSchemaObjectMinPropertiesv     = errorer.Wrapf(ErrJsonSchemaObjectMinProperties)
	ErrJsonSchemaObjectMaxMinProperties   = errorer.Errorf("maxProperties must be greater than minProperties")
	ErrJsonSchemaObjectMaxMinPropertiesv  = errorer.Wrapf(ErrJsonSchemaObjectMaxMinProperties)
	ErrJsonSchemaObjectPropertiesMissing  = errorer.Errorf("properties must be greater than 0")
)
