package model

import (
	"github.com/boundedinfinity/go-commoner/errorer"
)

var (
	ErrSchemaTypeNotFound       = errorer.Errorf("json schema type not found")
	ErrSchemaTypeUnsupported    = errorer.Errorf("json schema type unsupported")
	ErrSchemaTypeUnsupportedv   = errorer.Subf(ErrSchemaTypeUnsupported)
	ErrSchemaIdNotFound         = errorer.Errorf("json schema ID not found")
	ErrSchemaIdNotFoundv        = errorer.Subf(ErrSchemaIdNotFound)
	ErrSchemaCantResolve        = errorer.Errorf("json schema can't resolve")
	ErrSchemaCantResolvev       = errorer.Subf(ErrSchemaCantResolve)
	ErrSchemaIdDuplicate        = errorer.Errorf("json schema ID duplicate")
	ErrSchemaIdDuplicatev       = errorer.Subf(ErrSchemaIdDuplicate)
	ErrPathDuplicate            = errorer.Errorf("json schema path duplicate")
	ErrPathDuplicatev           = errorer.Subf(ErrPathDuplicate)
	ErrSchemaNotFound           = errorer.Errorf("json schema not found")
	ErrSchemaNotFoundv          = errorer.Subf(ErrSchemaNotFound)
	ErrRefEmpty                 = errorer.Errorf("reference is empty")
	ErrRefNotFound              = errorer.Errorf("reference not found")
	ErrRefNotFoundv             = errorer.Subf(ErrRefNotFound)
	ErrObjectPropertiesNotFound = errorer.Errorf("object properties not found")
	ErrSchemaTypeOrRefNotFound  = errorer.Errorf("json schema type or $ref not found missing")
	ErrMimeTypeUnsupported      = errorer.Errorf("MIME type unsupported")
	ErrMimeTypeUnsupportedv     = errorer.Subf(ErrMimeTypeUnsupported)
	ErrNumberMultipleOfInvalid  = errorer.Errorf("multipleOf must be greater than 0")
	ErrNumberMultipleOfInvalidv = errorer.Subf(ErrNumberMultipleOfInvalid)
	ErrArrayMaxContainsInvalid  = errorer.Errorf("maxContains must be greater than 0")
	ErrArrayMaxContainsInvalidv = errorer.Subf(ErrArrayMaxContainsInvalid)
	ErrArrayMinContainsInvalid  = errorer.Errorf("minContains must be greater than 0")
	ErrArrayMinContainsInvalidv = errorer.Subf(ErrArrayMinContainsInvalid)
	ErrArrayInvalidMaxMin       = errorer.Errorf("maxContains must be greater than minContains")
	ErrArrayInvalidMaxMinv      = errorer.Subf(ErrArrayInvalidMaxMin)
	ErrArrayItemsEmpty          = errorer.Errorf("array items is empty")
	ErrNumberInvalidMaxMin      = errorer.Errorf("maximum must be greater than minimum")
	ErrNumberInvalidMaxMinv     = errorer.Subf(ErrNumberInvalidMaxMin)
	ErrStringMaxLength          = errorer.Errorf("maxLength must be greater than 0")
	ErrStringMaxLengthv         = errorer.Subf(ErrStringMaxLength)
	ErrStringMinLength          = errorer.Errorf("minLength must be greater than 0")
	ErrStringMinLengthv         = errorer.Subf(ErrStringMinLength)
	ErrStringMaxMinLength       = errorer.Errorf("maxLength must be greater than minLength")
	ErrStringMaxMinLengthv      = errorer.Subf(ErrStringMaxMinLength)
	ErrObjectMaxProperties      = errorer.Errorf("maxProperties must be greater than 0")
	ErrObjectMaxPropertiesv     = errorer.Subf(ErrObjectMaxProperties)
	ErrObjectMinProperties      = errorer.Errorf("minProperties must be greater than 0")
	ErrObjectMinPropertiesv     = errorer.Subf(ErrObjectMinProperties)
	ErrObjectMaxMinProperties   = errorer.Errorf("maxProperties must be greater than minProperties")
	ErrObjectMaxMinPropertiesv  = errorer.Subf(ErrObjectMaxMinProperties)
	ErrObjectPropertiesMissing  = errorer.Errorf("properties must be greater than 0")
)
