//************************************************************************************
//*                                                                                  *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package jsonschema

import (
	"encoding/json"
	"fmt"
	"strings"
)

type JsonSchemaUriType string

const (
	JsonSchemaUriType_File    JsonSchemaUriType = "file"
	JsonSchemaUriType_Http    JsonSchemaUriType = "http"
	JsonSchemaUriType_Unknown JsonSchemaUriType = "unknown"
)

var (
	JsonSchemaUriTypeList = []JsonSchemaUriType{
		JsonSchemaUriType_File,
		JsonSchemaUriType_Http,
		JsonSchemaUriType_Unknown,
	}
)

func IsJsonSchemaUriType(v string) bool {
	var f bool

	for _, e := range JsonSchemaUriTypeList {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func JsonSchemaUriTypeParse(v string) (JsonSchemaUriType, error) {
	var o JsonSchemaUriType
	var f bool
	n := strings.ToLower(v)

	for _, e := range JsonSchemaUriTypeList {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, ErrJsonSchemaUriTypeNotFound(v)
	}

	return o, nil
}

func JsonSchemaUriTypeListToStrings(vs []JsonSchemaUriType) []string {
	var ss []string

	for _, v := range vs {
		ss = append(ss, v.String())
	}

	return ss
}

func ErrJsonSchemaUriTypeNotFound(v string) error {
	var ss []string

	for _, e := range JsonSchemaUriTypeList {
		ss = append(ss, string(e))
	}

	return fmt.Errorf(
		"invalid enumeration type '%v', must be one of %v",
		v, strings.Join(ss, ","),
	)
}

func (t JsonSchemaUriType) String() string {
	return string(t)
}

func (t JsonSchemaUriType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *JsonSchemaUriType) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := JsonSchemaUriTypeParse(s)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
