//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package uritype

import (
	"encoding/json"
	"fmt"
	"strings"
)

type UriType string
type UriTypes []UriType

const (
	File UriType = "file"
	Http UriType = "http"
)

var (
	All = UriTypes{
		File,
		Http,
	}
)

func Is(v string) bool {
	return All.Is(v)
}

func Parse(v string) (UriType, error) {
	return All.Parse(v)
}

func Strings() []string {
	return All.Strings()
}

func (t UriType) String() string {
	return string(t)
}

func errUriTypeInvalid(vs UriTypes, v string) error {
	return fmt.Errorf(
		"invalid enumeration type '%v', must be one of %v",
		v, strings.Join(vs.Strings(), ","),
	)
}

func (t UriTypes) Strings() []string {
	var ss []string

	for _, v := range t {
		ss = append(ss, v.String())
	}

	return ss
}

func (t UriTypes) Parse(v string) (UriType, error) {
	var o UriType
	var f bool
	n := strings.ToLower(v)

	for _, e := range t {
		if strings.ToLower(e.String()) == n {
			o = e
			f = true
			break
		}
	}

	if !f {
		return o, errUriTypeInvalid(t, v)
	}

	return o, nil
}

func (t UriTypes) Is(v string) bool {
	var f bool

	for _, e := range t {
		if string(e) == v {
			f = true
			break
		}
	}

	return f
}

func (t UriTypes) Contains(v UriType) bool {
	for _, e := range t {
		if e == v {
			return true
		}
	}

	return false
}

func (t UriType) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *UriType) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	e, err := Parse(s)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
